name: Code Quality
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [firebase_app, supabase_app]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: 'stable'
      - name: Create .env file
        run: |
          cd ${{ matrix.app }}
          cp .env.example .env
      - name: Get dependencies
        run: |
          cd ${{ matrix.app }}
          flutter pub get
      - name: Check formatting
        run: |
          cd ${{ matrix.app }}
          dart format --output=none --set-exit-if-changed .
      - name: Analyze code
        run: |
          cd ${{ matrix.app }}
          flutter analyze --fatal-infos
      - name: Check for outdated dependencies
        run: |
          cd ${{ matrix.app }}
          flutter pub outdated --exit-code
        continue-on-error: true
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'

